-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Erstellungszeit: 20. Dez 2025 um 20:13
-- Server-Version: 10.11.10-MariaDB-cll-lve-log
-- PHP-Version: 8.4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `dev_ausflugfinder`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `ausfluege`
--

CREATE TABLE `ausfluege` (
  `id` int(10) UNSIGNED NOT NULL,
  `user_id` int(10) UNSIGNED DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `beschreibung` text DEFAULT NULL,
  `adresse` varchar(255) NOT NULL,
  `land` varchar(50) DEFAULT 'Schweiz',
  `region` varchar(100) DEFAULT NULL,
  `kategorie_alt` varchar(100) DEFAULT NULL,
  `parkplatz` varchar(100) DEFAULT NULL,
  `parkplatz_kostenlos` tinyint(1) DEFAULT 0,
  `kosten_stufe` tinyint(4) DEFAULT NULL,
  `jahreszeiten` varchar(100) DEFAULT NULL,
  `website_url` varchar(255) DEFAULT NULL,
  `lat` decimal(10,7) DEFAULT NULL,
  `lng` decimal(10,7) DEFAULT NULL,
  `coordinates` point DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `nice_to_know` varchar(255) DEFAULT NULL,
  `dauer_min` decimal(5,2) DEFAULT NULL,
  `dauer_max` decimal(5,2) DEFAULT NULL,
  `distanz_min` decimal(6,2) DEFAULT NULL,
  `distanz_max` decimal(6,2) DEFAULT NULL,
  `dauer_stunden` decimal(5,2) DEFAULT NULL,
  `distanz_km` decimal(6,2) DEFAULT NULL,
  `is_rundtour` tinyint(1) NOT NULL DEFAULT 0,
  `is_von_a_nach_b` tinyint(1) NOT NULL DEFAULT 0,
  `altersempfehlung` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Daten für Tabelle `ausfluege`
--

INSERT INTO `ausfluege` (`id`, `user_id`, `name`, `beschreibung`, `adresse`, `land`, `region`, `kategorie_alt`, `parkplatz`, `parkplatz_kostenlos`, `kosten_stufe`, `jahreszeiten`, `website_url`, `lat`, `lng`, `coordinates`, `created_at`, `nice_to_know`, `dauer_min`, `dauer_max`, `distanz_min`, `distanz_max`, `dauer_stunden`, `distanz_km`, `is_rundtour`, `is_von_a_nach_b`, `altersempfehlung`) VALUES
(1, 1, 'Rulantica', 'Rulantica verspricht das ganze Jahr über Wasservergnügen für die ganze Familie: Ob Adrenalin-Junkies, Kleinkinder oder Entspannungssuchende – in der Wasserwelt ist für jeden etwas dabei.', 'Rulantica, Rust', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', 0, 4, 'all_year', 'https://www.europapark.de/de/rulantica', 48.2612350, 7.7398690, 0x000000000101000000014c1938a0f51e4008c9022670214840, '2025-09-03 08:09:36', 'grosse Badewelt,mit Aussenbereich,mit Innenbereich', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(4, 1, 'Bellis Mini-Freizeitpark', 'Geniessen Sie unbeschwerte Momente in unserem Mini-Freizeitpark inmitten der Natur. \r\nHier können sich Ihre Kinder austoben und Sie sich in aller Ruhe bei einem Cafe oder Gläschen Wein und leckerem Essen ausruhen.', 'Bellis Mini-Freizeitpark, Roggwil', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 1, 2, 'spring,summer,autumn', 'http://www.mini-freizeitpark.ch/', 47.2493313, 7.8219601, 0x000000000101000000b27790e8af491f4041af8916ea9f4740, '2025-09-03 22:25:26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(5, 1, 'Kiddy Dome', 'Auf mehr als 6.000 m2 Fläche und insgesamt fünf Ebenen findest du alles, was du für einen unvergesslichen Familienausflug brauchst. Egal, ob du mit deinem Baby, Kleinkind oder älteren Kindern kommst, wir haben für alle Altersgruppen die passenden Aktivitäten und Einrichtungen. In unseren Spielbereichen können deine Kinder sicher und kinderfreundlich klettern, rutschen, spielen und toben, während du dich in unserer gemütlichen Lounge entspannst.', 'Kiddy Dome, Rohrbach', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 1, 3, 'all_year', 'https://www.kiddydome.ch/', 47.1315220, 7.8186197, 0x00000000010100000001721d3e44461f402d5a80b6d5904740, '2025-09-03 22:28:32', 'grosser Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(6, 1, 'Pumptrack', 'Pumptrack Zell by Flying Metal', 'Pumptrack Zell by Flying Metal', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', 1, 0, 'spring,summer,autumn', 'https://www.zell-lu.ch/', 47.1379621, 7.9257474, 0x000000000101000000996d5d20f7b31f4033cbf9bda8914740, '2025-09-03 23:18:38', 'grosse Strecke,abwechslungsreiche Strecke', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(8, 1, 'Chugelibahn Seebodenalp', 'Auf der Seebodenalp gibt es neu einen Chugelbahnen-Weg, welcher Jung und Alt begeistert. Man macht sich mit einer grossen Holzkugel auf den Weg und kann an 11 verschiedenen Standorten spielen. Geniessen Sie herrliche Wanderungen mit schönem Ausblick und spannender Abwechslung. Der Rundweg wird gegen den Uhrzeigersinn empfohlen und ist auch so ausgeschildert. Man kann jedoch auch tageweise einzelne Bahnen bespielen. Da die Bahnen weit auseinander liegen, sollte man auch genügend Zeit einplanen.', 'Parkplatz, Seebodenalp', 'Schweiz', 'Nidwalden', NULL, '', 0, 3, 'spring,summer,autumn', 'https://www.chugelbahnen.ch/bahnen', 47.0689285, 8.4667938, 0x0000000001010000007df3d198ffee204094a12aa6d2884740, '2025-09-05 18:30:31', 'Grillstelle,Chugelibahn', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(10, 1, 'Abenteuerpfad Marbach', 'Start: Bergkäserei Marbach\r\nDie Ausrüstung für den \r\nAbenteuerpfad erhältst du von \r\nMontag bis Samstag in unserem \r\nVerkaufsladen und sonntags  \r\nam Automaten. \r\n\r\n\r\nErleben Sie auf dem zweistündigen Abenteuerpfad durch die Natur die Geschichte der drei Vögel Mar, Sol und Lou. Die Rauschschwalbe, die Bachstelze und der Spatz erzählen Ihnen viel Wissenswertes über ihre Vogelwelt.\r\n\r\n20 Posten mit interaktiven Spielen zum Entdecken, Staunen und Rätseln sowie eine einladende Schweizer-Familien-Feuerstelle führen von der Bergkäserei Marbach zum Arche-Hof Schangnau.\r\n\r\nUnsere jüngsten Gäste können sich auf eine Kinderspielecke im Käseerlebnis der Bergkäserei Marbach freuen.', 'Bergkäserei, Marbach', 'Schweiz', 'Luzern', NULL, '', 1, 2, 'spring,summer,autumn', 'https://www.kaeserei-marbach.ch/erleben/abenteuerpfad', 47.5707086, 16.0589364, 0x000000000101000000428bb674160f3040e245bafa0cc94740, '2025-09-05 23:29:54', 'Grillstelle', 2.00, 4.00, 8.00, 10.00, NULL, NULL, 0, 1, 'ab 12'),
(11, 1, 'Seeteufel', 'Umgeben von einer faszinierenden & naturbelassenden Pflanzenwelt beherbergt das beliebte Seeländer Ausflugsziel auf über 7 Hektaren mehr als 40 Tierarten aus allen 5 Erdteilen sowie zahlreiche Spiel- & Vergnügungsmöglichkeiten für Kinder zwischen 2 & 12 Jahren.', 'Seeteufel, Studen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 1, 3, 'all_year', 'https://www.seeteufel.ch/de/', 47.1115530, 7.3185740, 0x000000000101000000726c3d4338461d40a662635e478e4740, '2025-09-06 00:01:21', 'Familienfreundlichkeit', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(12, 1, 'Chärnsmatt', 'Die CHÄRNSMATT ist ein beliebtes Ausflugsziel und befindet sich in Rothenburg, gerade mal 10 Minuten von Luzern entfernt. Der Gasthof ist mit seinen schmucken Zimmern, das Restaurant mit den hausgemachten Pouletchnusperli und vor allem der riesengrosse Spielplatz mit eigener Liliputbahn machen die CHÄRNSMATT über die Kantonsgrenze hinaus bekannt und beliebt.', 'Chärnsmatt, Rothenburg', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', 1, 4, 'all_year', 'https://www.chaernsmatt.ch/', 47.0997871, 8.2707408, 0x000000000101000000c162c3899e8a20400688ddd2c58c4740, '2025-09-06 14:28:43', 'Aussenspielplatz,Kindermenüs,Kinderfreundlich,Innenspielplatz,Kinderstühle,Malset,Spielplatz abgeschirmt von der Strasse', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(13, 1, 'Freilichtmuseum Ballenberg', 'Tradition, die lebt. Unsere Wohnhäuser, Ställe und Scheunen sind täglich für Sie geöffnet.', 'Freilichtmuseum Ballenberg', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 0, 4, 'spring,summer,autumn', 'https://ballenberg.ch/de/', 46.7509031, 8.0777960, 0x000000000101000000ec8497e0d4272040867bc0971d604740, '2025-09-06 22:29:52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(14, 1, 'Europa Park', 'Im Herzen Europas, zwischen Schwarzwald und Vogesen, liegt einer der schönsten Freizeitparks der Welt. Seit 1975 begeistert der Europa-Park kleine und große Gäste mit seinem ganz besonderen Charme. Über 6 Millionen Besucher aller Nationen kommen jede Saison, um sich von über 100 Attraktionen und Shows begeistern und der detailverliebten Thematisierung verzaubern zu lassen!', 'Europa Park, Rust', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', 0, 4, 'spring,summer,autumn', 'https://www.europapark.de/de/park', 48.2660194, 7.7220076, 0x00000000010100000093dad5f555e31e40ff8c77ec0c224840, '2025-09-07 00:19:49', 'grosser Park', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(15, 1, 'Restaurant Pizzeria Landhaus', 'Es ist unser persönliches Anliegen, Ihren Aufenthalt im Landhaus zu einem Geschmackserlebnis zu gestalten. Küchenbrigade und Bedienung legen grossen Wert auf frische regionale Produkte, welche wir mit Sorgfalt verarbeiten. Geniessen Sie bei uns traditionsreiche Küche und das Ambiente des Hauses am reizvollen Thunersee.', 'Restaurant Pizzeria Landhaus, Unterseen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 1, 3, 'all_year', 'https://landhaus-interlaken.ch', 46.6820670, 7.8132300, 0x0000000001010000001b81785dbf401f402657b1f84d574740, '2025-09-07 16:10:28', 'Aussenspielplatz,Kinderfreundlich', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(16, 1, 'Glögglifroschweg', 'Willst du wissen, wo sich die Frösche besonders wohlfühlen? Der Glögglifroschweg Eich ist ein kleiner Erlebnisweg, welcher in Zusammenhang mit einem Artenförderungsprojekt für die gefährdete Geburtshelferkröte (Glögglifrosch) errichtet wurde.\r\nDieses kurze Teilstück des Eicher Rundweges startet am Dorfweiher. Direkt daneben gibt es viele Parkplätze. Auf der rechten Weiherseite findest du eine gemütliche Grillstelle. Der Glögglifroschweg startet auf der linken Seite des Dorfweihers. Siehst du den kleinen Tümpel? Vielleicht entdeckst du dort Frösche, welche die Sonnenstrahlen geniessen. Weiter führt der Pfad an einem Bach entlang – das Überqueren der kleinen Brücken macht besonders viel Spass. An warmen Tagen kannst du hier wunderbar deine Füsse ins Wasser tauchen und die Natur beobachten. Unterwegs findest du ausserdem mehrere aus Holz geschnitzte Figuren.\r\n\r\nDen Weg kannst du entweder am Schatten wieder zurückgehen oder du zweigst am Ende des Glögglifroschweges links ab und folgst der Naturstrasse in Richtung Dorf. An der Kirche und am Schulhaus vorbei kommst du direkt wieder zurück zum Parkplatz. Beim Schulhaus gibt es Toiletten und einen öffentlichen Spielplatz.\r\n\r\nWenn du noch mehr sehen möchtest, kannst du am Ende des Glögglifroschweges noch weiter dem Eicher Rundweg folgen und kommst so noch an diversen schönen Plätzen vorbei. Wenn du noch genug Energie hast, lohnt es sich, bis zum Oeleweiher weiterzugehen. Der Weg führt an einer Schlucht mit weiteren Brücken und Wasserfällen vorbei. Beim Oeleweiher gibt es eine gemütliche Bank zum Verweilen.', 'Glögglifroschweg, Eich', 'Schweiz', 'Luzern', NULL, '', 0, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/gloegglifroschweg-eich-lu/', 47.1521568, 8.1694166, 0x0000000001010000008dccc8c5bd56204098eebfdf79934740, '2025-09-07 20:31:01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(17, 1, 'Walderlebnispfad', 'Die kurze Rundwanderung startet beim Infopavillon auf dem Jungfernplatz und führt dich über den «Aufrechten Bären» bis zum höchsten Punkt im Roggwiler Wald. Unterwegs erwarten dich spannende Attraktionen und Informationstafeln zur Pflanzen- und Tierwelt des Waldes. Für Abwechslung sorgen verschiedene Spielposten wie eine Murmelbahn, eine Seilbahn und eindrucksvolle Holzskulpturen. Am Start- und Zielpunkt lädt ein grosser Spielplatz zum Verweilen und Spielen ein.', 'Walderlebnispfad, Roggwil', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', 1, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/walderlebnispfad-roggwil-be/', 47.2405859, 7.8235104, 0x000000000101000000dca96f4f464b1f407a30ce84cb9e4740, '2025-09-07 20:36:11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(18, 1, 'Kugelbahn-Rundweg, Oberiberg', 'Die Kugelbahn aus Lärchenholz, die in mehrere Teilstrecken aufgeteilt ist, sorgt für Spiel und Spass auf dieser idyllischen Wanderung durch das Feriendorf Oberiberg. Schaue zu, wie die Holzkugeln durch die Bahn rollen und dabei Hindernisse überwinden. Die Kugeln beziehst du für zwei Franken an einem Kugelautomaten, der sich bei der Bahn in der Michelmattstrasse befindet oder im Tourismusbüro an der Tschalunstrasse 1. Sorge dafür, dass du ein 2 Frankenstück dabei hast, da der Automat kein Kleingeld akzeptiert.\r\n\r\nKugelbahn Stationen:\r\n\r\nBeim Spielplatz Kirchenstrasse (Verkehrsveren Oberiberg)\r\nAuf dem Karl-Faber-Weg\r\nAusbau der Kugelbahn: Im Postwäldli gibt es neue Stationen zu entdecken. Freu dich auf spannende Erweiterungen und eine überarbeitete Streckenführung!', 'Kugelbahn-Rundweg, Oberiberg', 'Schweiz', 'Schwyz', NULL, 'genügend vorhanden', 0, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/kugelbahn-oberiberg-sz/', 47.0391614, 8.7817859, 0x000000000101000000a6f2d13d46902140fe21a23d03854740, '2025-09-07 21:03:40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL),
(19, 1, 'Grotte und Dino Park', 'Grotte und Dino Park', 'Grotte und Dino Park, Réclère', 'Schweiz', 'Jura', NULL, 'genügend vorhanden', 0, 2, 'spring,summer,autumn,winter', 'https://www.prehisto.ch/index.php/fr/', 47.3589213, 6.9142950, 0x000000000101000000d595cff23ca81b403dab1622f1ad4740, '2025-09-07 21:41:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(20, 1, 'Sauriermuseum Aathal', 'Entdecken Sie bei uns ...\r\n\r\nechte Dinosaurierskelette aus eigener Grabung\r\ndiverse Spezialausstellungen zu Themen wie Bernstein, fossilen Pflanzen usw.\r\nden Aussenbereich \"DinoGiardino\" mit Spiel- und Picknickplatz\r\nunseren Dino-Shop und den \"RockShop\" für alles was der Saurier- und Fossilienfan begehrt!', 'Sauriermuseum, Aathal', 'Schweiz', 'Zürich', NULL, 'genügend vorhanden', 1, 4, 'all_year', 'https://www.sauriermuseum.ch/', 47.3388227, 8.7619400, 0x0000000001010000004a07ebff1c8621403bd2cf8a5eab4740, '2025-09-07 22:34:29', 'Aussenspielplatz,Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(36, 1, 'Abenteuerweg - Ahoi Piraten!', 'Im Hörspiel treffen die Geschwister Winnie & Tack auf Helgi, der fürs Leben gerne Pirat werden möchte. Als sie dann auch noch auf eine Piratencrew treffen, geht’s wild zu und her.', 'Bahnhofstrasse 37, Fehraltorf', 'Schweiz', 'Zürich', NULL, '', 0, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3853129, 8.7499615, 0x000000000101000000a98427f4fa7f21400c1de0ee51b14740, '2025-09-14 21:15:24', 'Kinderwagentauglich,Grillstelle,Abenteuer,Smartphone', 3.00, 4.00, 4.00, 6.00, NULL, NULL, 0, 1, '7-12'),
(37, 1, 'Abenteuerweg - Der Diamantring', 'In Egg hören Winnie & Tack von einer Einbruchserie. Sie verfolgen die Spuren und versuchen die Täter zu entlarven. Doch schon bald schweben sie in grosser Gefahr.', 'Forchstrasse 178, Hinteregg', 'Schweiz', 'Zürich', NULL, '', 0, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3060295, 8.6840753, 0x000000000101000000b600231e3f5e21403d0e83f92ba74740, '2025-09-14 21:22:29', 'Abenteuer,Smartphone', 3.00, 4.00, 5.00, 6.00, NULL, NULL, 0, 1, '7-12'),
(38, 1, 'Abenteuerweg - Die Suche nach Silber', 'In Mönchaltorf suchen Winnie & Tack nach alten Silbermünzen. Dabei werden sie Zeugen eines Überfalls und verfolgen den Dieb. Zusätzlich treffen sie eine Rangerin, welche ihnen viel neues über die Tierwelt erzählt.', 'Silbergruebstrasse 55a, Mönchaltorf', 'Schweiz', 'Zürich', NULL, '', 0, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3077428, 8.7230938, 0x00000000010100000077e1bd5939722140c1898d1e64a74740, '2025-09-14 21:24:37', 'Abenteuer,Smartphone', 2.00, 4.00, 4.00, 6.00, NULL, NULL, 0, 1, '7-12'),
(39, 1, 'Abenteuerweg - Winnie & Tack helfen der Magierin', 'Auf der Suche nach den Symbolen auf der Karte treffen Winnie & Tack auf eine verzauberte Magierin. Hilf ihnen sich bei ihrem Abenteuer richtig zu entscheiden.', 'Dorfplatz 1, Meilen', 'Schweiz', 'Zürich', NULL, '', 0, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.1807609, 8.4593324, 0x0000000001010000005bd9f45613322140461273ff47a14740, '2025-09-14 21:30:03', 'Abenteuer,Smartphone', 3.00, 4.00, 5.00, 7.00, NULL, NULL, 1, 0, '7-12'),
(40, 1, 'Smartphone Schnitzeljagd - Hexenkraft', 'Die Hexe \"Mary\" ist verzweifelt. Die Oberhexe hat ihr alle Hexenkräfte weggenommen. Es gibt nur eine Möglichkeit, diese zurückzugewinnen. An verschiedenen Standorten befinden sich verschiedene Rätsel. Erst wenn diese gelöst werden, kann Mary wieder fliegen, in die Zukunft sehen und zaubern.\r\n\r\nGemeinsam mit Mary macht Ihr Euch auf den Weg zu den verschiedenen Orten. Nur wenn alle Rätsel gelöst sind, kann der Hexe Mary geholfen werden.', 'Altstadt, Sursee', 'Schweiz', 'Luzern', NULL, '', 0, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/hexenkraft/', 47.1724320, 8.1109560, 0x00000000010100000007978e39cf3820405664744012964740, '2025-09-14 21:51:07', 'Smartphone', 1.50, 2.00, 1.50, 1.50, NULL, NULL, 0, 0, NULL),
(41, 1, 'Smartphone Schnitzeljagd - Schatzsuche', 'Der kleine Pirat Jack liebt es, wenn ihm sein Grossvater die Geschichte des gefürchteten Piraten John Holzbein und seiner Mannschaft erzählt.  Nach einer stürmischen Nacht war das Schiff und die ganze Piratenbande plötzlich spurlos verschwunden. Bis heute wurde das Piratenschiff mit all seinen Schätzen an Board nicht gefunden und man hat nie mehr etwas von John Holzbein und seiner Mannschaft gehört. \r\n\r\nGemeinsam mit dem Piraten Jack macht ihr Euch auf den abenteuerlichen Weg und sucht den verlorenen Schatz am Lungernsee. Nur wenn alle Rätsel richtig gelöst werden, findet man das Versteck der Schatzkiste heraus', 'Lungern', 'Schweiz', 'Obwalden', NULL, '', 0, 2, NULL, 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/schatzsuche/', 46.7858188, 8.1597040, 0x000000000101000000ad1402b9c45120407e4adfb595644740, '2025-09-14 22:00:34', 'Smartphone', 1.50, 2.00, 2.00, 2.00, NULL, NULL, 0, 0, NULL),
(42, 1, 'Smartphone Schnitzeljagd - Nachtgespenst', 'Das Gespenst \"Lumi\" ist traurig, denn die anderen Gespenster haben es in ein Taggespenst verwandelt. \"Lumi\" mag den Tag aber nicht, weil es zu hell und zu laut ist. Könnt ihr \"Lumi\" helfen, wieder ein Nachtgespenst zu werden?\r\n\r\nGemeinsam mit Lumi macht Ihr Euch auf dem Weg zu den verschiedenen Orten. Nur wenn alle Rätsel gelöst sind, kann dem Gespenst Lumi geholfen werden.', 'Hintere Vorstadt, Aarau', 'Schweiz', 'Aargau', NULL, '', 0, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/nachtgespenst/', 47.3913454, 8.0454691, 0x00000000010100000005f5d2b9471720405338279b17b24740, '2025-09-14 22:08:59', 'Smartphone', 1.50, 2.00, 1.50, 1.50, NULL, NULL, 0, 0, NULL),
(43, 1, 'Smartphone Schnitzeljagd - Drachenfreund', 'Der Papagei Cleo wurde von seinem Freund dem Drachen um Hilfe gebeten. Der Drache ist schwer krank. Er erzählte Cleo, dass eine grosse starke Tanne weiss wie er wieder Gesund werden kann. \r\n\r\n \r\n\r\nZusammen mit Cleo macht Ihr euch auf den abenteuerlichen Märchenweg durch den Wald von Heiligkreuz. Nur wenn alle Rätsel richtig gelöst werden, könnt ihr dem Drachen helfen, wieder Gesund zu werden.   \r\n\r\nDie Geschichte Drachenfreund basiert auf dem Märchen \"Wurzilla und der Drache von Heiligkreuz\" von Lisbeth Scheidegger-Lieb.', 'Heiligkreuz, 6166 Hasle', 'Schweiz', 'Luzern', NULL, '', 0, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/drachenfreund/', 46.9461955, 8.0558211, 0x0000000001010000007eda4d95941c2040aa0f24ef1c794740, '2025-09-14 22:10:41', 'Smartphone', 1.00, 1.50, 1.00, 1.00, NULL, NULL, 0, 0, NULL),
(44, 1, 'Schmugglis Schatzsuche', 'Vor vielen Jahren legte der Schmuggler Engelbert gemeinsam mit seinem Maultier Schmuggli regelmässig den mühsamen Weg von Engelberg über den Jochpass bis zur Engstlenalp zurück. Dabei versteckten sie ihre Schmuggelwaren an verschiedenen Stellen rund um den Trübsee.\r\n\r\nAn jedem der sieben Spielplätze in der Umgebung des Trübsees findest du jeweils ein Zeichen mit einem Buchstaben. Stanze diesen Buchstaben in die dafür vorgesehenen Felder deiner Schmugglerkarte ein, und wenn du das korrekte Lösungswort herausfindest, kannst du einen grossartigen Schmuggli-Preis gewinnen.\r\n\r\n__________________________________________________________\r\n\r\nDie Schmugglerkarte findest du im Flyer zu Schmugglis Erlebniswelt. Den Flyer erhältst du an der Titlis Talstation oder bei der Station Trübsee. Stanze bei den sechs Spielstationen den Buchstaben in das jeweilige Feld.\r\n\r\n_______________________________________________________\r\n\r\nDu kannst dein Schmuggli-Geschenk an diesen Orten abholen:\r\n\r\nTrübsee: Self-Service Restaurant im Berghotel Trübsee\r\nTalstation: Ausgangskiosk, Restaurant Linie 8, Kasse\r\n\r\nLass dich überraschen!', 'Titlis Talstation', 'Schweiz', 'Obwalden', NULL, '', 0, 0, 'spring,summer,autumn', 'https://www.schmugglis-erlebniswelt.ch/de/schatzsuche#start', 46.8161706, 8.3957541, 0x0000000001010000000d840948a0ca2040757a394778684740, '2025-09-14 22:18:49', 'Kinderwagentauglich,Abenteuer', 1.00, 1.00, NULL, NULL, NULL, NULL, 1, 0, '2-10'),
(45, 1, 'Schmugglis Sbrinz Weg das Rätsel', 'Die historische Sbrinz Route führt von Luzern über Engelberg bis nach Domodossola. Hierhin wurde früher der beliebte Sbrinz Käse gebracht und gegen Olivenöl, Rotwein und andere italienische Güter getauscht. Schmuggler Engelbert und sein Maultier Schmuggli versuchen zwischen Trübsee und der Alp Untertrübsee sechs knifflige Rätsel zu lösen und dabei von Zöllnern und Hexen unentdeckt zu bleiben. Folge ihnen, löse die Aufgaben und versuche das richtige Lösungswort herauszufinden. Du kannst attraktive Preise gewinnen.', 'Titlis, Engelberg', 'Schweiz', 'Obwalden', NULL, '', 0, 1, 'summer,autumn', 'https://www.schmugglis-erlebniswelt.ch/de/sbrinz#start', 46.8206098, 8.4023803, 0x000000000101000000fe1b6aca04ce204078e3eebd09694740, '2025-09-14 22:24:00', 'Abenteuer', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(46, 1, 'Schmugglis Spielplatz', 'Hier entdeckst du die versteckten Schätze von Engelbert und seinem Maultier Schmuggli. Überquere dann den Bach und geniesse entspannt dein leckeres Picknick im Säumerlager. Holz und Grillstellen sind vorhanden und frei nutzbar.', 'Spielplatz, Trübsee', 'Schweiz', 'Obwalden', NULL, '', 0, 1, 'spring,summer,autumn,winter', 'https://www.schmugglis-erlebniswelt.ch/de/spielplatz#start', 46.7944762, 8.3899300, 0x0000000001010000006475abe7a4c72040a5396865b1654740, '2025-09-14 22:29:14', 'WC vorhanden,Picknicktische,fuer Kleinkinder geeignet,mit Restaurant/Kiosk', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(47, 1, 'Sikypark - Schweizer Tierrettungspark', 'Der Sikypark sorgt dafür, dass einheimische und exotische Wildtiere in Not ein gutes Zuhause erhalten. Dafür betreibt er eine Seniorenresidenz für Raubtiere, eine Papageienstation sowie die Station Mami für verletzte oder verwaiste einheimische Wildtiere. Was den Tierbestand betrifft, ist der Sikypark kein klassischer Zoo. Über 90 Prozent der über 850 Schützlinge stammen aus Rettungen, d.h. aus Beschlagnahmungen durch Veterinärämter oder Abgaben durch Zirkusse, Zoos oder Private. Durch diese spezielle Herkunft der Tiere und dem zum Teil ausgeprägten Menschenbezug, ergeben sich für die Besucher aussergewöhnliche Interaktionsmöglichkeiten die in Erinnerung bleiben. Das Sikypark-Team setzt sich täglich mit Herzblut für das Wohl der tierischen Bewohner ein. Lernen Sie die Schützlinge bei einem Besuch kennen und unterstützen Sie damit die wichtige Mission des Schweizer Tierrettungsparks.', 'Sikypark, Crémines', 'Schweiz', 'Bern', NULL, '', 0, 2, 'all_year', 'https://www.sikypark.ch/', 47.2736250, 7.4555123, 0x000000000101000000f5b3fdd071d21d401b2fdd2406a34740, '2025-09-14 22:45:50', 'Erlebnis & Programm,Familienfreundlichkeit', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(48, 1, 'Spielhaus Stalla Libra', 'Das Spielhaus Stalla Libra im Herzen von Sedrun wurde mit jungen Gestaltern des Royal College of Art in London entwickelt. Im ungenutzten Stall könnt ihr kostenlos an verschiedenen Spielstationen testen, wie viel Geschick, Kreativität und Ausdauer in euch steckt.', 'Spielhaus Stalla Libra, Sedrun', 'Schweiz', 'Graubünden', NULL, '', 0, 0, 'summer,autumn,winter', 'https://www.stalla-libra.ch/spielhaus.html', 46.6811028, 8.7761915, 0x000000000101000000cadde7f8688d2140659b65602e574740, '2025-09-14 22:49:35', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(49, 1, 'Wasserwald & Vogeldörfli', 'Der Wasserwald auf Furt, eine einzigartige Wasserspielanlage, steht ganz im Zeichen von Spiel und Action rund um das Thema Wasser. Von Wasserspielgeräten am natürlichen Bachlauf bis hin zu interaktiven Spritzbrunnen und Rinnenlabyrinthen gibt es hier alles, was das Kinderherz begehrt.\r\nBeim Freilichtmuseum können die Kinder eigene Vogelhäuser bauen und ausstellen.', 'Wasserwald & Vogeldörfli, Bad Ragaz', 'Schweiz', 'St. Gallen', NULL, '', 0, 0, 'spring,summer,autumn', 'https://pizol.com/erlebnisse/wasserwald/', 47.0010950, 9.4162540, 0x0000000001010000008ba8893e1fd52240359886e123804740, '2025-09-14 22:58:16', 'Wasserspiel', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(50, 1, 'MounTeens Detektiv-Weg', 'Erlebe mit den MounTeens ein spannendes Abenteuer auf dem MounTeens Detektiv-Weg am Pizol, entdecke die Umgebung und hilf mit, den Fall zu lösen.\r\n\r\nDie MounTeens – das sind die Dreizehnjährigen Sam, Lena, Matteo und Amélie, die mutig und scharfsinnig Detektivabenteuer lösen. Die MounTeens sind auf einem Wanderausflug mit der Schulklasse am Pizol. Kurz bevor sie von ihrem Lehrer in Vierergruppen auf einen Postenlauf geschickt werden, taucht ein völlig verängstigter Wanderer auf, der von lauten Schreien berichtet. Treibt hier ein Berggeist sein Unwesen? Hilf den MounTeens, den Fall zu lösen und entdecke dabei die Umgebung.\r\n\r\nAn der Kasse der Talstation Wangs gibt es das exklusive Detektiv-Wanderbuch dazu. Zu jedem der 10 Posten gibt es ein dazugehöriges Kapitel. Wer sich lieber die Geschichte vorlesen lassen will, kann neben jedem Kapitel-Titel einen QR-Code mit dem Smartphone scannen.\r\n\r\nUnterwegs kommen wir am Wasserwald vorbei, wo rund um das Thema Wasser viel gespielt und entdeckt werden kann.\r\n\r\nAutorentipp:\r\nWer mag, steigt in Wangs in eine der fünf Gondeln im MounTeens-Look und lernt Sam, Lena, Matteo und Amélie bereits während der Fahrt näher kennen.', 'Pizolstrasse 3, 7323 Wangs', 'Schweiz', 'St. Gallen', NULL, '', 0, 0, 'spring,summer,autumn', 'https://outdoor.heidiland.com/de/tour/themenweg/mounteens-detektiv-weg/42754051/?utm_medium=referral&utm_source=embed&utm_campaign=embed-plugin-referral&utm_term=https%3A%2F%2Fpizol.com%2F#dmdtab=oax-tab1', 47.0280926, 9.4332824, 0x00000000010100000062ddd330d7dd22403b21cf8998834740, '2025-09-14 23:03:52', 'Smartphone', 1.50, 1.50, 2.10, 2.10, NULL, NULL, 0, 0, NULL),
(51, 1, 'Kugelweg Hasliberg', 'Entlang des Wanderweges von der Mittelstation Bidmi zur Talstation Reuti erwarten Sie 13 spannende und abwechslungsreiche Kugelbahnen. Die Bahnen wurden von einheimischen Holzbaufirmen und einer Metallbaufirma konstruiert.\r\n\r\nKugeln für den Kugelweg sind an den Kassen der Bergbahnen, im Bergshop Mägisalp, im Familienrestaurant Bidmi sowie im Hotel Reuti erhältlich. Der Preis pro Kugel beträgt CHF 3.00.\r\n\r\nDie einzige Grillstelle auf dem Kugelweg befindet sich gleich nach der ersten Kugelbahn in Bidmi am Bidmisee.\r\nHolz zum Feuer machen ist vorhanden.', 'Bidmi, Hasliberg', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 0, 2, 'summer', 'https://meiringen-hasliberg.ch/17/kugelweg-hasliberg', 46.7440448, 8.2187993, 0x00000000010100000080c63b7606702040226129dc3c5f4740, '2025-09-15 12:59:27', 'Grillstelle,Chugelibahn', 1.50, 1.50, 3.00, 3.00, NULL, NULL, 0, 1, NULL),
(52, 1, 'Zwergenspielplatz Bidmi', 'Bei unserem Zwergenspielplatz in der Bidmi ist immer etwas los...\r\n\r\nDer neu erbaute Spielplatz ganz im Motto der Haslizwerge bietet eine abwechslungsreiche Austobmöglichkeit für Kinder, mit vielen kreativen und geschichtsbezogenen Elementen. Dazu gibt es eine komfortable Brätelstelle am Rande des Bidmiseelis mit Aussicht auf die wunderschöne Wetterhorngruppe.', 'Zwergenspielplatz Bidmi', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 0, 2, 'summer', 'https://meiringen-hasliberg.ch/3/zwergenspielplatz-bidmi', 46.7441962, 8.2181007, 0x0000000001010000002c781be5aa6f20405b6732d2415f4740, '2025-09-15 13:07:15', 'Picknicktische,Zaun/abgeschlossen', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(53, 1, 'Zwergenweg Mägisalp-Bidmi', 'Abenteuer auf dem Zwergenweg\r\nDie Haslizwerge haben in unserem Tal eine lange Tradition und Muggestutz ist der älteste Haslizwerg. Auf dem Zwergenweg Mägisalp-Bidmi erlebt er unzählige Abenteuer, welche die Kinder bei den Erlebnisposten wie Tannzapfentröchni, Adlerschaukel und Höhle spielerisch nachvollziehen können.\r\n\r\nDer Weg verläuft leicht abwärts über Alpweiden und durch Tannenwälder. Auf dem Weg gibt es mehrere Rastplätze, welche das Bräteln in der freien Natur ermöglichen.', 'Zwergenweg Muggestutz', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 0, 2, 'summer', 'https://meiringen-hasliberg.ch/2/zwergenweg-magisalp-bidmi', 46.7447276, 8.2369945, 0x000000000101000000eba9d55757792040db36e73b535f4740, '2025-09-15 13:14:06', 'Grillstelle', 2.00, 2.00, 5.00, 5.00, NULL, NULL, 0, 1, NULL),
(54, 1, 'Rufalipark', 'Das Rufalipark Kinderspielparadies mit rund 300m² lässt für Kinder zwischen 1 und 10 Jahren keine Wünsche offen. Ein kunterbuntes Klettergerüst und ein Geschicklichkeits­parcours aus Holz und Seilen bieten genügend Spielfläche für die Kids um sich auszutoben, zu rutschen, zu klettern und neue Bewegungsformen auszutesten.\r\n\r\nPackt das Badezeug ein. An schönen Tagen könnt ihr euch im Badesee erfrischen.', 'Rufalipark, Obersaxen', 'Schweiz', 'Graubünden', NULL, '', 0, 0, 'all_year', 'https://rufalipark.ch/', 46.7510929, 9.1205880, 0x0000000001010000008194d8b5bd3d224000e1e8cf23604740, '2025-09-15 13:22:10', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(55, 1, 'Energiespielplatz Entlebuch', 'Mit Spiel und Spass nachhaltige Energien entdecken\r\nJe mehr Kinder hier sind, desto spannender wird es auf dem Energiespielplatz Entlebuch, denn viele der Spielgeräte sind miteinander verknüpft. Die grösseren Kids schaufeln wie wild Holzschnitzel auf ein Förderband, und befördern die Schnitzel mittels Kurbeln in die Höhe, wo sie in einen Metalltrichter fallen. Damit wird ein Schaufelrad angetrieben, das wiederum eine Pumpe in Betrieb setzt. Die Geduld wird belohnt, denn nun sprudelt das Wasser Richtung Wassergraben und setzt dabei das Wasserrad in Bewegung.\r\n\r\nDer Wassergraben wird aber auch von anderer Seite her weiter gefüllt: Beim «Wasserschloss» kann kurbelnd ein Wasserstrahl erzeugt werden, es gilt den einige Meter entfernten Metallbehälter zu treffen, der das Wasser in einen Holzkanal leitet, den sogenannten «Holzweg». In diesem Holzkanal kann das Wasser über verschiedene Wege umgeleitet, gestaut oder portionenweise zum Graben abgelassen werden. Ein Riesenspass, nicht nur für Nachwuchs-Ingenieure. Auch bei den Windrädern, dem «Windstoss» kann weiteres Wasser für den Graben produziert werden. Je mehr davon im Umlauf gerät, desto lustiger wird natürlich das Leben auf dem Energiespielplatz. Ganz nebenbei lernen die Kinder aber auch nachhaltige Energien kennen und erzeugen diese selber. Auch die Kleinsten kommen auf ihre Rechnung beim Planschen mit dem Wasser oder auf der Schaukel.', 'Energiespielplatz, Entlebuch', 'Schweiz', 'Luzern', NULL, '', 0, 0, 'all_year', 'https://www.biosphaere.ch/de/poi/energiespielplatz-entlebuch', 46.9878541, 8.0592686, 0x000000000101000000025c3574581e2040195cce00727e4740, '2025-09-15 13:32:57', 'Wasserspiel', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(56, 1, 'Abenteuerspielplatz Fröschenmatt', 'Holz schleppen, sägen, hämmern, bauen, malen, basteln und vieles mehr. Hier darfst du eigene Hütten bauen und es gibt einiges mehr zu entdecken.\r\n\r\nDer Abenteuerspielplatz Fröschenmatt begrüsst seit 50 Jahren grosse und kleine Besucher auf dem 5‘800m2 grossen Areal am Steinhauser Fussweg. Der Spielplatz bietet den Kindern genügend Platz zum Spielen, Klettern und auch, um ihre Kreativität auszuleben. Der Abenteuerspielplatz  bietet eine grosse Bastelecke und eine Hämmerwerkstatt. Im grossen Freilaufgehege der Ziegen darf gesägt und gehämmert werden. Es entstehen einzigartige Hütten und sogar Ritterburgen.\r\n\r\nAber auch für die ganz kleinen Gäste gibt es nebst den Tieren genügend Beschäftigung im Sandkasten, wo die vorhandenen Sandspielsachen zum Sändele motivieren. Eine Grillstelle steht den Besuchern zur Verfügung.\r\n\r\nDer Spielplatz ist nur an bestimmten Zeiten geöffnet. Während diesen Zeiten sind Betreuungspersonen anwesend, und stehen den Kindern mit Rat und Tat zur Seite. Je nach Saison wird zudem ein Glaceverkauf oder für die Erwachsenen ein Kaffee angeboten.', 'Abenteuerspielplatz Fröschenmatt, Zug', 'Schweiz', 'Zug', NULL, '', 0, 0, 'spring,summer,autumn', 'https://www.froeschi.ch', 47.1813381, 8.4951151, 0x000000000101000000f482f4b97ffd204067823c1636974740, '2025-09-16 12:52:18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(57, 1, 'Augusta Raurica', 'Augusta Raurica birgt eine Vielzahl historischer Schätze, darunter ein mysteriöser Brunnen, der als der größte Silberschatz aus der Spätantike gilt, sowie einen begehbaren Abwasserkanal römischen Ursprungs. Diese faszinierende Stätte ist buchstäblich eine Fundgrube für Geschichte und bietet unendliche Geheimnisse zum Entdecken.', 'Giebenacherstrasse 17, 4302 Augst', 'Schweiz', 'Basel-Landschaft', NULL, 'genügend vorhanden', 0, 1, 'all_year', 'https://www.augustaraurica.ch/', 47.5340444, 7.7215489, 0x000000000101000000eedbffb6dde21e40544e20915bc44740, '2025-09-16 12:55:21', 'Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(58, 1, 'Tierpark Goldau', 'Der Natur- und Tierpark Goldau liegt eingebettet in einer einzigartigen Landschaft, geprägt von imposanten Felsbrocken und idyllischen Wäldern. Der Park bietet Lebensraum für über 100 Wildtierarten, darunter Bären, Wölfe und Luchse, sowie zahlreiche weitere einheimische Tierarten. Mit einem Fokus auf Natur- und Artenschutz, Bildung und Forschung verfolgt der Natur- und Tierpark Goldau wichtige ideelle Ziele:\r\n\r\nNaturschutz\r\nWir setzen uns aktiv für den Erhalt und die Förderung der Biodiversität ein. Unsere Naturschutzflächen sind Zufluchtsorte für viele Tierarten und wichtige Amphibien-Laichgebiete von nationaler Bedeutung.\r\n\r\nArtenschutz\r\nDurch regelmässige Auswilderungen, die Teilnahme an internationalen Erhaltungszuchtprogrammen und den Erhalt einer gesunden Reservepopulation leisten wir einen wesentlichen Beitrag zum Artenschutz. Die länderübergreifenden Bemühungen von Zoos und Tierpark haben bereits viele Arten vor dem Aussterben bewahrt.\r\n\r\nBildung\r\nUnsere Bildungsprogramme sensibilisieren jährlich zehntausende Besuchenden für die Bedeutung des Natur- und Artenschutzes und motivieren sie, sich aktiv für die Umwelt einzusetzen. Schulen nutzen den Park als ausserschulischen Lernort. Ausstellungen, kommentierte Fütterungen, Tierbeobachtungen und Exponate helfen, Wissen zu vertiefen.\r\n\r\nForschung\r\nEin Grossteil unseres Wissens über Tiere und ihr Verhalten stammt aus der Forschung in Zoos und Wildparks. Der Natur- und Tierpark Goldau arbeitet mit Universitäten zusammen, um wissenschaftliche Projekte zu unterstützen und unser Verständnis für die Tierwelt kontinuierlich zu erweitern.', 'Tierpark, Goldau', 'Schweiz', 'Schwyz', NULL, 'genügend vorhanden', 0, 3, 'all_year', 'https://www.tierpark.ch/', 47.0514811, 8.5539168, 0x000000000101000000f26899fb9a1b2140596ec4ee96864740, '2025-09-16 13:00:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(59, 1, 'Connyland', 'CONNY-LAND, da wirst du was erleben!\r\nBaden mit Seelöwen, kreischen auf der Cobra und auf Entdeckungs­tour im Jungle.\r\nLust auf Spass und Abenteuer? Freue dich auf fröhliche Abenteuer und unvergessliche Momente mit der ganzen Familie! Unsere vielen Attraktionen garantieren für einen vergnüglichen, kurzweiligen und unbeschwerten Tag! Bei uns finden grosse und kleine Kinder ihr Glück!\r\n\r\nEin Tag im CONNY-LAND … so viel mehr als du erwartest!', 'Connyland, Wäldi', 'Schweiz', 'Thurgau', NULL, 'genügend vorhanden', 0, 3, 'spring,summer,autumn', 'https://www.connyland.ch/', 47.6143550, 9.0574462, 0x000000000101000000178f9c96691d22402a91442fa3ce4740, '2025-09-16 13:04:48', 'mittlerer Park', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(60, 1, 'Erlebnisweg Teufenthal', 'Die Sage vom Schloss Liebegg und der Trostburg ist unterwegs in 7 Teilen zu lesen. Die Tafeln mit der Sage befinden sich jeweils bei den Ruhebänkli. Ebenso stehen für die kleinen Abenteurer 7 Kugelbahnen zur Verfügung, welche vom Teufenthaler Gewerbe erstellt wurden. Die Kugeln können am Kugelautomaten beim Gemeindehaus für 2 Franken bezogen werden.\r\n\r\nDer Rundweg führt von 450 m.ü.M hinauf auf die Hochrüti, über Dreiangel und Cholholz weiter hoch zur Breiti auf 564 m.ü.M. Richtung Süden erblickt man die Alpen und im Norden die Jurakette. Von da aus geht es das Tannholz hinunter. Am Chilchweg befindet sich eine Grillstelle, an der es sich am Brunnen und Mülibach verweilen lässt. Nach gemütlicher Pause geht die Strecke dem Wald entlang Richtung Werkhof/Friedhof weiter, wo sich das letzte Sitzbänkli auf der Route befindet. Zurück zum Dorfplatz führen die letzten 500 Meter durch das Dorf Teufenthal.\r\n\r\nDer Erlebnisweg entstand als Gewinner-Projekt des Partizipativen Budgets 2024 und wurde durch eine Projektgruppe aus Freiwilligen mit Hilfe des lokalen Gewerbes umgesetzt.', 'Erlebnisweg, Teufenthal', 'Schweiz', 'Aargau', NULL, 'genügend vorhanden', 1, 1, 'all_year', 'https://www.teufenthal.ch/freizeit/erlebnisweg-teufenthal.html/471', 47.3276148, 8.1186489, 0x000000000101000000aa69728cbf3c2040c1d72148efa94740, '2025-09-29 12:40:05', 'Kinderwagentauglich,Grillstelle,Chugelibahn', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(62, 1, 'Laguna Badeland', 'Den größten Genuss erlebt der Schwimmer, wenn er in der wohltemperierten Brandung des über 40 m langen Wellenbecken schwimmt und durch die große Glaspyramide in den Himmel oder in den Abendstunden zu den Sternen schauen kann.', 'Laguna Badeland, Weil am Rhein', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', 0, 2, 'all_year', 'https://laguna-badeland.de', 47.5862114, 7.6157682, 0x000000000101000000caaa63f08b761e406dc5a3f908cb4740, '2025-10-01 15:50:31', 'kleine Badewelt,mit Aussenbereich,mit Innenbereich', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(66, 1, 'Kambly Erlebniswelt', 'Entdecken Sie in der Erlebniswelt von Kambly den Ursprung der Traditionsmarke und begeben Sie sich mit Kambly auf Entdeckungstour durch das Emmental.', 'Kambly, Trubschachen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', 1, 0, 'all_year', 'https://kambly.com/de/kambly-erlebnis/erlebniswelt/', 46.9203513, 7.8496591, 0x000000000101000000c4fefc080d661f40612a4712ce754740, '2025-10-05 12:36:25', 'Innenspielplatz,Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(69, 1, 'KidsVille', 'Der Kletterdschungel bietet den Kindern unzählige Wege, Tunnel und Klettermöglichkeiten. Es gibt wahnsinnig viel zu entdecken beim Abenteuer durch das Dschungel-Labyrinth. Die \"Bergsteiger\" werden mutig den Vulkan erklimmen, während die kleinen \"Tarzans\" und \"Janes\" den Dschungel erforschen und immer wieder auf neue Hindernisse sowie verspielte Ecken und Wege treffen.\r\n\r\nIm Baumhaus oder auf der Bergspitze angekommen, entscheiden sich die Abenteurer dann, ob Sie den Abstieg durch die vielen verwinkelten Wege und Höhlen in Angriff nehmen oder wagemutig eine der diversen Rutschbahnen wählen, um dann mit Saus und Braus ins Tal zu schlittern.\r\n\r\nNicht fehlen darf natürlich der Soft-Ball-Shooter-Bereich mit den vielen bunten Bällen und das integrierte grosse Trampolin, welches zum unbeschwerten Hüpfen und Springen einlädt. \r\n  \r\nDie Highlights dieses Bereichs in der Übersicht \r\nKletterdschungel mit vielen Abenteuerwegen und Hindernissen\r\ngrosses Trampolin\r\nModerne Softball-Shooter\r\nDiverse Rutschbahnen\r\nVulkan-Kletterwand\r\nBaumhäuser mit toller Aussicht Rutschbahnen direkt ins bunte Bällebad', 'KidsVille, Aarau', 'Schweiz', 'Aargau', NULL, '', 0, 1, 'all_year', 'https://www.bowlingcenteraarau.ch/angebote-und-preise/kids-ville/', 47.3949818, 8.0644745, 0x00000000010100000016da39cd02212040f2c17cc38eb24740, '2025-10-07 20:00:42', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL),
(78, 1, 'Lasertag', 'Lasertag ist ein Actionspiel, das Teamfähigkeit und Geschick gegen die Gegner erfordert. Im riesigen, mehrstöckigen Areal befinden sich Rampen, Balkone, geniale Deckungen, Hindernisse und ein Flugzeug. Spielen Sie auf der mit Abstand grössten, modernsten und spektakulärsten Lasergame Anlage der Schweiz.', 'Actionworld, Obfelden', 'Schweiz', '', NULL, '', 0, 4, 'all_year', 'https://www.actionworld.ch/lasertag?gad_source=1&gad_campaignid=887183496&gbraid=0AAAAADKE_EwLLQkIrViT6r49Pgd3KNIqf&gclid=CjwKCAiAwqHIBhAEEiwAx9cTeXkaBJgux720QTlsvfcynvz3Ga0lP50b1RMLO5gMQfowUPjpvcon_xoCfVQQAvD_BwE', 47.2663571, 8.4228132, NULL, '2025-11-03 15:39:24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL);

--
-- Trigger `ausfluege`
--
DELIMITER $$
CREATE TRIGGER `ausfluege_insert_coordinates` BEFORE INSERT ON `ausfluege` FOR EACH ROW BEGIN
IF NEW.lat IS NOT NULL AND NEW.lng IS NOT NULL THEN
SET NEW.coordinates = POINT(NEW.lng, NEW.lat);
END IF;
END
$$
DELIMITER ;

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `ausfluege`
--
ALTER TABLE `ausfluege`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `region` (`region`),
  ADD KEY `kosten_stufe` (`kosten_stufe`),
  ADD KEY `idx_lat_lng` (`lat`,`lng`),
  ADD KEY `idx_needs_geocoding` (`lat`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `ausfluege`
--
ALTER TABLE `ausfluege`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;

--
-- Constraints der exportierten Tabellen
--

--
-- Constraints der Tabelle `ausfluege`
--
ALTER TABLE `ausfluege`
  ADD CONSTRAINT `fk_ausfluege_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
