-- Migration script for ausfluege data from MySQL to Supabase PostgreSQL
-- Generated: 2025-12-20
-- Total records: 45 trips

-- First, clear existing data (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE ausfluege RESTART IDENTITY CASCADE;

-- Insert all trips
INSERT INTO ausfluege (id, user_id, name, beschreibung, adresse, land, region, kategorie_alt, parkplatz, parkplatz_kostenlos, kosten_stufe, jahreszeiten, website_url, lat, lng, created_at, nice_to_know, dauer_min, dauer_max, distanz_min, distanz_max, dauer_stunden, distanz_km, is_rundtour, is_von_a_nach_b, altersempfehlung) VALUES
(1, 1, 'Rulantica', 'Rulantica verspricht das ganze Jahr über Wasservergnügen für die ganze Familie: Ob Adrenalin-Junkies, Kleinkinder oder Entspannungssuchende – in der Wasserwelt ist für jeden etwas dabei.', 'Rulantica, Rust', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', false, 4, 'all_year', 'https://www.europapark.de/de/rulantica', 48.2612350, 7.7398690, '2025-09-03 08:09:36', 'grosse Badewelt,mit Aussenbereich,mit Innenbereich', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(4, 1, 'Bellis Mini-Freizeitpark', 'Geniessen Sie unbeschwerte Momente in unserem Mini-Freizeitpark inmitten der Natur. 
Hier können sich Ihre Kinder austoben und Sie sich in aller Ruhe bei einem Cafe oder Gläschen Wein und leckerem Essen ausruhen.', 'Bellis Mini-Freizeitpark, Roggwil', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', true, 2, 'spring,summer,autumn', 'http://www.mini-freizeitpark.ch/', 47.2493313, 7.8219601, '2025-09-03 22:25:26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(5, 1, 'Kiddy Dome', 'Auf mehr als 6.000 m2 Fläche und insgesamt fünf Ebenen findest du alles, was du für einen unvergesslichen Familienausflug brauchst. Egal, ob du mit deinem Baby, Kleinkind oder älteren Kindern kommst, wir haben für alle Altersgruppen die passenden Aktivitäten und Einrichtungen. In unseren Spielbereichen können deine Kinder sicher und kinderfreundlich klettern, rutschen, spielen und toben, während du dich in unserer gemütlichen Lounge entspannst.', 'Kiddy Dome, Rohrbach', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', true, 3, 'all_year', 'https://www.kiddydome.ch/', 47.1315220, 7.8186197, '2025-09-03 22:28:32', 'grosser Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(6, 1, 'Pumptrack', 'Pumptrack Zell by Flying Metal', 'Pumptrack Zell by Flying Metal', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', true, 0, 'spring,summer,autumn', 'https://www.zell-lu.ch/', 47.1379621, 7.9257474, '2025-09-03 23:18:38', 'grosse Strecke,abwechslungsreiche Strecke', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(8, 1, 'Chugelibahn Seebodenalp', 'Auf der Seebodenalp gibt es neu einen Chugelbahnen-Weg, welcher Jung und Alt begeistert. Man macht sich mit einer grossen Holzkugel auf den Weg und kann an 11 verschiedenen Standorten spielen. Geniessen Sie herrliche Wanderungen mit schönem Ausblick und spannender Abwechslung. Der Rundweg wird gegen den Uhrzeigersinn empfohlen und ist auch so ausgeschildert. Man kann jedoch auch tageweise einzelne Bahnen bespielen. Da die Bahnen weit auseinander liegen, sollte man auch genügend Zeit einplanen.', 'Parkplatz, Seebodenalp', 'Schweiz', 'Nidwalden', NULL, '', false, 3, 'spring,summer,autumn', 'https://www.chugelbahnen.ch/bahnen', 47.0689285, 8.4667938, '2025-09-05 18:30:31', 'Grillstelle,Chugelibahn', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(10, 1, 'Abenteuerpfad Marbach', E'Start: Bergkäserei Marbach\r\nDie Ausrüstung für den \r\nAbenteuerpfad erhältst du von \r\nMontag bis Samstag in unserem \r\nVerkaufsladen und sonntags  \r\nam Automaten. \r\n\r\n\r\nErleben Sie auf dem zweistündigen Abenteuerpfad durch die Natur die Geschichte der drei Vögel Mar, Sol und Lou. Die Rauschschwalbe, die Bachstelze und der Spatz erzählen Ihnen viel Wissenswertes über ihre Vogelwelt.\r\n\r\n20 Posten mit interaktiven Spielen zum Entdecken, Staunen und Rätseln sowie eine einladende Schweizer-Familien-Feuerstelle führen von der Bergkäserei Marbach zum Arche-Hof Schangnau.\r\n\r\nUnsere jüngsten Gäste können sich auf eine Kinderspielecke im Käseerlebnis der Bergkäserei Marbach freuen.', 'Bergkäserei, Marbach', 'Schweiz', 'Luzern', NULL, '', true, 2, 'spring,summer,autumn', 'https://www.kaeserei-marbach.ch/erleben/abenteuerpfad', 47.5707086, 16.0589364, '2025-09-05 23:29:54', 'Grillstelle', 2.00, 4.00, 8.00, 10.00, NULL, NULL, false, true, 'ab 12'),
(11, 1, 'Seeteufel', 'Umgeben von einer faszinierenden & naturbelassenden Pflanzenwelt beherbergt das beliebte Seeländer Ausflugsziel auf über 7 Hektaren mehr als 40 Tierarten aus allen 5 Erdteilen sowie zahlreiche Spiel- & Vergnügungsmöglichkeiten für Kinder zwischen 2 & 12 Jahren.', 'Seeteufel, Studen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', true, 3, 'all_year', 'https://www.seeteufel.ch/de/', 47.1115530, 7.3185740, '2025-09-06 00:01:21', 'Familienfreundlichkeit', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(12, 1, 'Chärnsmatt', 'Die CHÄRNSMATT ist ein beliebtes Ausflugsziel und befindet sich in Rothenburg, gerade mal 10 Minuten von Luzern entfernt. Der Gasthof ist mit seinen schmucken Zimmern, das Restaurant mit den hausgemachten Pouletchnusperli und vor allem der riesengrosse Spielplatz mit eigener Liliputbahn machen die CHÄRNSMATT über die Kantonsgrenze hinaus bekannt und beliebt.', 'Chärnsmatt, Rothenburg', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', true, 4, 'all_year', 'https://www.chaernsmatt.ch/', 47.0997871, 8.2707408, '2025-09-06 14:28:43', 'Aussenspielplatz,Kindermenüs,Kinderfreundlich,Innenspielplatz,Kinderstühle,Malset,Spielplatz abgeschirmt von der Strasse', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(13, 1, 'Freilichtmuseum Ballenberg', 'Tradition, die lebt. Unsere Wohnhäuser, Ställe und Scheunen sind täglich für Sie geöffnet.', 'Freilichtmuseum Ballenberg', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', false, 4, 'spring,summer,autumn', 'https://ballenberg.ch/de/', 46.7509031, 8.0777960, '2025-09-06 22:29:52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(14, 1, 'Europa Park', 'Im Herzen Europas, zwischen Schwarzwald und Vogesen, liegt einer der schönsten Freizeitparks der Welt. Seit 1975 begeistert der Europa-Park kleine und große Gäste mit seinem ganz besonderen Charme. Über 6 Millionen Besucher aller Nationen kommen jede Saison, um sich von über 100 Attraktionen und Shows begeistern und der detailverliebten Thematisierung verzaubern zu lassen!', 'Europa Park, Rust', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', false, 4, 'spring,summer,autumn', 'https://www.europapark.de/de/park', 48.2660194, 7.7220076, '2025-09-07 00:19:49', 'grosser Park', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(15, 1, 'Restaurant Pizzeria Landhaus', 'Es ist unser persönliches Anliegen, Ihren Aufenthalt im Landhaus zu einem Geschmackserlebnis zu gestalten. Küchenbrigade und Bedienung legen grossen Wert auf frische regionale Produkte, welche wir mit Sorgfalt verarbeiten. Geniessen Sie bei uns traditionsreiche Küche und das Ambiente des Hauses am reizvollen Thunersee.', 'Restaurant Pizzeria Landhaus, Unterseen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', true, 3, 'all_year', 'https://landhaus-interlaken.ch', 46.6820670, 7.8132300, '2025-09-07 16:10:28', 'Aussenspielplatz,Kinderfreundlich', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(16, 1, 'Glögglifroschweg', E'Willst du wissen, wo sich die Frösche besonders wohlfühlen? Der Glögglifroschweg Eich ist ein kleiner Erlebnisweg, welcher in Zusammenhang mit einem Artenförderungsprojekt für die gefährdete Geburtshelferkröte (Glögglifrosch) errichtet wurde.\r\nDieses kurze Teilstück des Eicher Rundweges startet am Dorfweiher. Direkt daneben gibt es viele Parkplätze. Auf der rechten Weiherseite findest du eine gemütliche Grillstelle. Der Glögglifroschweg startet auf der linken Seite des Dorfweihers. Siehst du den kleinen Tümpel? Vielleicht entdeckst du dort Frösche, welche die Sonnenstrahlen geniessen. Weiter führt der Pfad an einem Bach entlang – das Überqueren der kleinen Brücken macht besonders viel Spass. An warmen Tagen kannst du hier wunderbar deine Füsse ins Wasser tauchen und die Natur beobachten. Unterwegs findest du ausserdem mehrere aus Holz geschnitzte Figuren.\r\n\r\nDen Weg kannst du entweder am Schatten wieder zurückgehen oder du zweigst am Ende des Glögglifroschweges links ab und folgst der Naturstrasse in Richtung Dorf. An der Kirche und am Schulhaus vorbei kommst du direkt wieder zurück zum Parkplatz. Beim Schulhaus gibt es Toiletten und einen öffentlichen Spielplatz.\r\n\r\nWenn du noch mehr sehen möchtest, kannst du am Ende des Glögglifroschweges noch weiter dem Eicher Rundweg folgen und kommst so noch an diversen schönen Plätzen vorbei. Wenn du noch genug Energie hast, lohnt es sich, bis zum Oeleweiher weiterzugehen. Der Weg führt an einer Schlucht mit weiteren Brücken und Wasserfällen vorbei. Beim Oeleweiher gibt es eine gemütliche Bank zum Verweilen.', 'Glögglifroschweg, Eich', 'Schweiz', 'Luzern', NULL, '', false, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/gloegglifroschweg-eich-lu/', 47.1521568, 8.1694166, '2025-09-07 20:31:01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(17, 1, 'Walderlebnispfad', 'Die kurze Rundwanderung startet beim Infopavillon auf dem Jungfernplatz und führt dich über den «Aufrechten Bären» bis zum höchsten Punkt im Roggwiler Wald. Unterwegs erwarten dich spannende Attraktionen und Informationstafeln zur Pflanzen- und Tierwelt des Waldes. Für Abwechslung sorgen verschiedene Spielposten wie eine Murmelbahn, eine Seilbahn und eindrucksvolle Holzskulpturen. Am Start- und Zielpunkt lädt ein grosser Spielplatz zum Verweilen und Spielen ein.', 'Walderlebnispfad, Roggwil', 'Schweiz', 'Luzern', NULL, 'genügend vorhanden', true, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/walderlebnispfad-roggwil-be/', 47.2405859, 7.8235104, '2025-09-07 20:36:11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(18, 1, 'Kugelbahn-Rundweg, Oberiberg', E'Die Kugelbahn aus Lärchenholz, die in mehrere Teilstrecken aufgeteilt ist, sorgt für Spiel und Spass auf dieser idyllischen Wanderung durch das Feriendorf Oberiberg. Schaue zu, wie die Holzkugeln durch die Bahn rollen und dabei Hindernisse überwinden. Die Kugeln beziehst du für zwei Franken an einem Kugelautomaten, der sich bei der Bahn in der Michelmattstrasse befindet oder im Tourismusbüro an der Tschalunstrasse 1. Sorge dafür, dass du ein 2 Frankenstück dabei hast, da der Automat kein Kleingeld akzeptiert.\r\n\r\nKugelbahn Stationen:\r\n\r\nBeim Spielplatz Kirchenstrasse (Verkehrsveren Oberiberg)\r\nAuf dem Karl-Faber-Weg\r\nAusbau der Kugelbahn: Im Postwäldli gibt es neue Stationen zu entdecken. Freu dich auf spannende Erweiterungen und eine überarbeitete Streckenführung!', 'Kugelbahn-Rundweg, Oberiberg', 'Schweiz', 'Schwyz', NULL, 'genügend vorhanden', false, 0, 'spring,summer,autumn', 'https://www.kinderwanderwege.ch/wanderweg/kugelbahn-oberiberg-sz/', 47.0391614, 8.7817859, '2025-09-07 21:03:40', NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, NULL),
(19, 1, 'Grotte und Dino Park', 'Grotte und Dino Park', 'Grotte und Dino Park, Réclère', 'Schweiz', 'Jura', NULL, 'genügend vorhanden', false, 2, 'spring,summer,autumn,winter', 'https://www.prehisto.ch/index.php/fr/', 47.3589213, 6.9142950, '2025-09-07 21:41:35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(20, 1, 'Sauriermuseum Aathal', E'Entdecken Sie bei uns ...\r\n\r\nechte Dinosaurierskelette aus eigener Grabung\r\ndiverse Spezialausstellungen zu Themen wie Bernstein, fossilen Pflanzen usw.\r\nden Aussenbereich \"DinoGiardino\" mit Spiel- und Picknickplatz\r\nunseren Dino-Shop und den \"RockShop\" für alles was der Saurier- und Fossilienfan begehrt!', 'Sauriermuseum, Aathal', 'Schweiz', 'Zürich', NULL, 'genügend vorhanden', true, 4, 'all_year', 'https://www.sauriermuseum.ch/', 47.3388227, 8.7619400, '2025-09-07 22:34:29', 'Aussenspielplatz,Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(36, 1, 'Abenteuerweg - Ahoi Piraten!', 'Im Hörspiel treffen die Geschwister Winnie & Tack auf Helgi, der fürs Leben gerne Pirat werden möchte. Als sie dann auch noch auf eine Piratencrew treffen, geht''s wild zu und her.', 'Bahnhofstrasse 37, Fehraltorf', 'Schweiz', 'Zürich', NULL, '', false, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3853129, 8.7499615, '2025-09-14 21:15:24', 'Kinderwagentauglich,Grillstelle,Abenteuer,Smartphone', 3.00, 4.00, 4.00, 6.00, NULL, NULL, false, true, '7-12'),
(37, 1, 'Abenteuerweg - Der Diamantring', 'In Egg hören Winnie & Tack von einer Einbruchserie. Sie verfolgen die Spuren und versuchen die Täter zu entlarven. Doch schon bald schweben sie in grosser Gefahr.', 'Forchstrasse 178, Hinteregg', 'Schweiz', 'Zürich', NULL, '', false, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3060295, 8.6840753, '2025-09-14 21:22:29', 'Abenteuer,Smartphone', 3.00, 4.00, 5.00, 6.00, NULL, NULL, false, true, '7-12'),
(38, 1, 'Abenteuerweg - Die Suche nach Silber', 'In Mönchaltorf suchen Winnie & Tack nach alten Silbermünzen. Dabei werden sie Zeugen eines Überfalls und verfolgen den Dieb. Zusätzlich treffen sie eine Rangerin, welche ihnen viel neues über die Tierwelt erzählt.', 'Silbergruebstrasse 55a, Mönchaltorf', 'Schweiz', 'Zürich', NULL, '', false, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.3077428, 8.7230938, '2025-09-14 21:24:37', 'Abenteuer,Smartphone', 2.00, 4.00, 4.00, 6.00, NULL, NULL, false, true, '7-12'),
(39, 1, 'Abenteuerweg - Winnie & Tack helfen der Magierin', 'Auf der Suche nach den Symbolen auf der Karte treffen Winnie & Tack auf eine verzauberte Magierin. Hilf ihnen sich bei ihrem Abenteuer richtig zu entscheiden.', 'Dorfplatz 1, Meilen', 'Schweiz', 'Zürich', NULL, '', false, 0, 'all_year', 'https://abenteuerweg.ch/orte.html', 47.1807609, 8.4593324, '2025-09-14 21:30:03', 'Abenteuer,Smartphone', 3.00, 4.00, 5.00, 7.00, NULL, NULL, true, false, '7-12'),
(40, 1, 'Smartphone Schnitzeljagd - Hexenkraft', E'Die Hexe \"Mary\" ist verzweifelt. Die Oberhexe hat ihr alle Hexenkräfte weggenommen. Es gibt nur eine Möglichkeit, diese zurückzugewinnen. An verschiedenen Standorten befinden sich verschiedene Rätsel. Erst wenn diese gelöst werden, kann Mary wieder fliegen, in die Zukunft sehen und zaubern.\r\n\r\nGemeinsam mit Mary macht Ihr Euch auf den Weg zu den verschiedenen Orten. Nur wenn alle Rätsel gelöst sind, kann der Hexe Mary geholfen werden.', 'Altstadt, Sursee', 'Schweiz', 'Luzern', NULL, '', false, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/hexenkraft/', 47.1724320, 8.1109560, '2025-09-14 21:51:07', 'Smartphone', 1.50, 2.00, 1.50, 1.50, NULL, NULL, false, false, NULL),
(41, 1, 'Smartphone Schnitzeljagd - Schatzsuche', E'Der kleine Pirat Jack liebt es, wenn ihm sein Grossvater die Geschichte des gefürchteten Piraten John Holzbein und seiner Mannschaft erzählt.  Nach einer stürmischen Nacht war das Schiff und die ganze Piratenbande plötzlich spurlos verschwunden. Bis heute wurde das Piratenschiff mit all seinen Schätzen an Board nicht gefunden und man hat nie mehr etwas von John Holzbein und seiner Mannschaft gehört. \r\n\r\nGemeinsam mit dem Piraten Jack macht ihr Euch auf den abenteuerlichen Weg und sucht den verlorenen Schatz am Lungernsee. Nur wenn alle Rätsel richtig gelöst werden, findet man das Versteck der Schatzkiste heraus', 'Lungern', 'Schweiz', 'Obwalden', NULL, '', false, 2, NULL, 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/schatzsuche/', 46.7858188, 8.1597040, '2025-09-14 22:00:34', 'Smartphone', 1.50, 2.00, 2.00, 2.00, NULL, NULL, false, false, NULL),
(42, 1, 'Smartphone Schnitzeljagd - Nachtgespenst', E'Das Gespenst \"Lumi\" ist traurig, denn die anderen Gespenster haben es in ein Taggespenst verwandelt. \"Lumi\" mag den Tag aber nicht, weil es zu hell und zu laut ist. Könnt ihr \"Lumi\" helfen, wieder ein Nachtgespenst zu werden?\r\n\r\nGemeinsam mit Lumi macht Ihr Euch auf dem Weg zu den verschiedenen Orten. Nur wenn alle Rätsel gelöst sind, kann dem Gespenst Lumi geholfen werden.', 'Hintere Vorstadt, Aarau', 'Schweiz', 'Aargau', NULL, '', false, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/nachtgespenst/', 47.3913454, 8.0454691, '2025-09-14 22:08:59', 'Smartphone', 1.50, 2.00, 1.50, 1.50, NULL, NULL, false, false, NULL),
(43, 1, 'Smartphone Schnitzeljagd - Drachenfreund', E'Der Papagei Cleo wurde von seinem Freund dem Drachen um Hilfe gebeten. Der Drache ist schwer krank. Er erzählte Cleo, dass eine grosse starke Tanne weiss wie er wieder Gesund werden kann. \r\n\r\n \r\n\r\nZusammen mit Cleo macht Ihr euch auf den abenteuerlichen Märchenweg durch den Wald von Heiligkreuz. Nur wenn alle Rätsel richtig gelöst werden, könnt ihr dem Drachen helfen, wieder Gesund zu werden.   \r\n\r\nDie Geschichte Drachenfreund basiert auf dem Märchen \"Wurzilla und der Drache von Heiligkreuz\" von Lisbeth Scheidegger-Lieb.', 'Heiligkreuz, 6166 Hasle', 'Schweiz', 'Luzern', NULL, '', false, 2, 'all_year', 'https://www.smartphone-schnitzeljagd-family.ch/geschichten/drachenfreund/', 46.9461955, 8.0558211, '2025-09-14 22:10:41', 'Smartphone', 1.00, 1.50, 1.00, 1.00, NULL, NULL, false, false, NULL),
(44, 1, 'Schmugglis Schatzsuche', E'Vor vielen Jahren legte der Schmuggler Engelbert gemeinsam mit seinem Maultier Schmuggli regelmässig den mühsamen Weg von Engelberg über den Jochpass bis zur Engstlenalp zurück. Dabei versteckten sie ihre Schmuggelwaren an verschiedenen Stellen rund um den Trübsee.\r\n\r\nAn jedem der sieben Spielplätze in der Umgebung des Trübsees findest du jeweils ein Zeichen mit einem Buchstaben. Stanze diesen Buchstaben in die dafür vorgesehenen Felder deiner Schmugglerkarte ein, und wenn du das korrekte Lösungswort herausfindest, kannst du einen grossartigen Schmuggli-Preis gewinnen.\r\n\r\n__________________________________________________________\r\n\r\nDie Schmugglerkarte findest du im Flyer zu Schmugglis Erlebniswelt. Den Flyer erhältst du an der Titlis Talstation oder bei der Station Trübsee. Stanze bei den sechs Spielstationen den Buchstaben in das jeweilige Feld.\r\n\r\n_______________________________________________________\r\n\r\nDu kannst dein Schmuggli-Geschenk an diesen Orten abholen:\r\n\r\nTrübsee: Self-Service Restaurant im Berghotel Trübsee\r\nTalstation: Ausgangskiosk, Restaurant Linie 8, Kasse\r\n\r\nLass dich überraschen!', 'Titlis Talstation', 'Schweiz', 'Obwalden', NULL, '', false, 0, 'spring,summer,autumn', 'https://www.schmugglis-erlebniswelt.ch/de/schatzsuche#start', 46.8161706, 8.3957541, '2025-09-14 22:18:49', 'Kinderwagentauglich,Abenteuer', 1.00, 1.00, NULL, NULL, NULL, NULL, true, false, '2-10'),
(45, 1, 'Schmugglis Sbrinz Weg das Rätsel', 'Die historische Sbrinz Route führt von Luzern über Engelberg bis nach Domodossola. Hierhin wurde früher der beliebte Sbrinz Käse gebracht und gegen Olivenöl, Rotwein und andere italienische Güter getauscht. Schmuggler Engelbert und sein Maultier Schmuggli versuchen zwischen Trübsee und der Alp Untertrübsee sechs knifflige Rätsel zu lösen und dabei von Zöllnern und Hexen unentdeckt zu bleiben. Folge ihnen, löse die Aufgaben und versuche das richtige Lösungswort herauszufinden. Du kannst attraktive Preise gewinnen.', 'Titlis, Engelberg', 'Schweiz', 'Obwalden', NULL, '', false, 1, 'summer,autumn', 'https://www.schmugglis-erlebniswelt.ch/de/sbrinz#start', 46.8206098, 8.4023803, '2025-09-14 22:24:00', 'Abenteuer', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(46, 1, 'Schmugglis Spielplatz', 'Hier entdeckst du die versteckten Schätze von Engelbert und seinem Maultier Schmuggli. Überquere dann den Bach und geniesse entspannt dein leckeres Picknick im Säumerlager. Holz und Grillstellen sind vorhanden und frei nutzbar.', 'Spielplatz, Trübsee', 'Schweiz', 'Obwalden', NULL, '', false, 1, 'spring,summer,autumn,winter', 'https://www.schmugglis-erlebniswelt.ch/de/spielplatz#start', 46.7944762, 8.3899300, '2025-09-14 22:29:14', 'WC vorhanden,Picknicktische,fuer Kleinkinder geeignet,mit Restaurant/Kiosk', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(47, 1, 'Sikypark - Schweizer Tierrettungspark', 'Der Sikypark sorgt dafür, dass einheimische und exotische Wildtiere in Not ein gutes Zuhause erhalten. Dafür betreibt er eine Seniorenresidenz für Raubtiere, eine Papageienstation sowie die Station Mami für verletzte oder verwaiste einheimische Wildtiere. Was den Tierbestand betrifft, ist der Sikypark kein klassischer Zoo. Über 90 Prozent der über 850 Schützlinge stammen aus Rettungen, d.h. aus Beschlagnahmungen durch Veterinärämter oder Abgaben durch Zirkusse, Zoos oder Private. Durch diese spezielle Herkunft der Tiere und dem zum Teil ausgeprägten Menschenbezug, ergeben sich für die Besucher aussergewöhnliche Interaktionsmöglichkeiten die in Erinnerung bleiben. Das Sikypark-Team setzt sich täglich mit Herzblut für das Wohl der tierischen Bewohner ein. Lernen Sie die Schützlinge bei einem Besuch kennen und unterstützen Sie damit die wichtige Mission des Schweizer Tierrettungsparks.', 'Sikypark, Crémines', 'Schweiz', 'Bern', NULL, '', false, 2, 'all_year', 'https://www.sikypark.ch/', 47.2736250, 7.4555123, '2025-09-14 22:45:50', 'Erlebnis & Programm,Familienfreundlichkeit', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(48, 1, 'Spielhaus Stalla Libra', 'Das Spielhaus Stalla Libra im Herzen von Sedrun wurde mit jungen Gestaltern des Royal College of Art in London entwickelt. Im ungenutzten Stall könnt ihr kostenlos an verschiedenen Spielstationen testen, wie viel Geschick, Kreativität und Ausdauer in euch steckt.', 'Spielhaus Stalla Libra, Sedrun', 'Schweiz', 'Graubünden', NULL, '', false, 0, 'summer,autumn,winter', 'https://www.stalla-libra.ch/spielhaus.html', 46.6811028, 8.7761915, '2025-09-14 22:49:35', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(49, 1, 'Wasserwald & Vogeldörfli', E'Der Wasserwald auf Furt, eine einzigartige Wasserspielanlage, steht ganz im Zeichen von Spiel und Action rund um das Thema Wasser. Von Wasserspielgeräten am natürlichen Bachlauf bis hin zu interaktiven Spritzbrunnen und Rinnenlabyrinthen gibt es hier alles, was das Kinderherz begehrt.\r\nBeim Freilichtmuseum können die Kinder eigene Vogelhäuser bauen und ausstellen.', 'Wasserwald & Vogeldörfli, Bad Ragaz', 'Schweiz', 'St. Gallen', NULL, '', false, 0, 'spring,summer,autumn', 'https://pizol.com/erlebnisse/wasserwald/', 47.0010950, 9.4162540, '2025-09-14 22:58:16', 'Wasserspiel', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(50, 1, 'MounTeens Detektiv-Weg', E'Erlebe mit den MounTeens ein spannendes Abenteuer auf dem MounTeens Detektiv-Weg am Pizol, entdecke die Umgebung und hilf mit, den Fall zu lösen.\r\n\r\nDie MounTeens – das sind die Dreizehnjährigen Sam, Lena, Matteo und Amélie, die mutig und scharfsinnig Detektivabenteuer lösen. Die MounTeens sind auf einem Wanderausflug mit der Schulklasse am Pizol. Kurz bevor sie von ihrem Lehrer in Vierergruppen auf einen Postenlauf geschickt werden, taucht ein völlig verängstigter Wanderer auf, der von lauten Schreien berichtet. Treibt hier ein Berggeist sein Unwesen? Hilf den MounTeens, den Fall zu lösen und entdecke dabei die Umgebung.\r\n\r\nAn der Kasse der Talstation Wangs gibt es das exklusive Detektiv-Wanderbuch dazu. Zu jedem der 10 Posten gibt es ein dazugehöriges Kapitel. Wer sich lieber die Geschichte vorlesen lassen will, kann neben jedem Kapitel-Titel einen QR-Code mit dem Smartphone scannen.\r\n\r\nUnterwegs kommen wir am Wasserwald vorbei, wo rund um das Thema Wasser viel gespielt und entdeckt werden kann.\r\n\r\nAutorentipp:\r\nWer mag, steigt in Wangs in eine der fünf Gondeln im MounTeens-Look und lernt Sam, Lena, Matteo und Amélie bereits während der Fahrt näher kennen.', 'Pizolstrasse 3, 7323 Wangs', 'Schweiz', 'St. Gallen', NULL, '', false, 0, 'spring,summer,autumn', 'https://outdoor.heidiland.com/de/tour/themenweg/mounteens-detektiv-weg/42754051/', 47.0280926, 9.4332824, '2025-09-14 23:03:52', 'Smartphone', 1.50, 1.50, 2.10, 2.10, NULL, NULL, false, false, NULL),
(51, 1, 'Kugelweg Hasliberg', E'Entlang des Wanderweges von der Mittelstation Bidmi zur Talstation Reuti erwarten Sie 13 spannende und abwechslungsreiche Kugelbahnen. Die Bahnen wurden von einheimischen Holzbaufirmen und einer Metallbaufirma konstruiert.\r\n\r\nKugeln für den Kugelweg sind an den Kassen der Bergbahnen, im Bergshop Mägisalp, im Familienrestaurant Bidmi sowie im Hotel Reuti erhältlich. Der Preis pro Kugel beträgt CHF 3.00.\r\n\r\nDie einzige Grillstelle auf dem Kugelweg befindet sich gleich nach der ersten Kugelbahn in Bidmi am Bidmisee.\r\nHolz zum Feuer machen ist vorhanden.', 'Bidmi, Hasliberg', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', false, 2, 'summer', 'https://meiringen-hasliberg.ch/17/kugelweg-hasliberg', 46.7440448, 8.2187993, '2025-09-15 12:59:27', 'Grillstelle,Chugelibahn', 1.50, 1.50, 3.00, 3.00, NULL, NULL, false, true, NULL),
(52, 1, 'Zwergenspielplatz Bidmi', E'Bei unserem Zwergenspielplatz in der Bidmi ist immer etwas los...\r\n\r\nDer neu erbaute Spielplatz ganz im Motto der Haslizwerge bietet eine abwechslungsreiche Austobmöglichkeit für Kinder, mit vielen kreativen und geschichtsbezogenen Elementen. Dazu gibt es eine komfortable Brätelstelle am Rande des Bidmiseelis mit Aussicht auf die wunderschöne Wetterhorngruppe.', 'Zwergenspielplatz Bidmi', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', false, 2, 'summer', 'https://meiringen-hasliberg.ch/3/zwergenspielplatz-bidmi', 46.7441962, 8.2181007, '2025-09-15 13:07:15', 'Picknicktische,Zaun/abgeschlossen', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(53, 1, 'Zwergenweg Mägisalp-Bidmi', E'Abenteuer auf dem Zwergenweg\r\nDie Haslizwerge haben in unserem Tal eine lange Tradition und Muggestutz ist der älteste Haslizwerg. Auf dem Zwergenweg Mägisalp-Bidmi erlebt er unzählige Abenteuer, welche die Kinder bei den Erlebnisposten wie Tannzapfentröchni, Adlerschaukel und Höhle spielerisch nachvollziehen können.\r\n\r\nDer Weg verläuft leicht abwärts über Alpweiden und durch Tannenwälder. Auf dem Weg gibt es mehrere Rastplätze, welche das Bräteln in der freien Natur ermöglichen.', 'Zwergenweg Muggestutz', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', false, 2, 'summer', 'https://meiringen-hasliberg.ch/2/zwergenweg-magisalp-bidmi', 46.7447276, 8.2369945, '2025-09-15 13:14:06', 'Grillstelle', 2.00, 2.00, 5.00, 5.00, NULL, NULL, false, true, NULL),
(54, 1, 'Rufalipark', 'Das Rufalipark Kinderspielparadies mit rund 300m² lässt für Kinder zwischen 1 und 10 Jahren keine Wünsche offen. Ein kunterbuntes Klettergerüst und ein Geschicklichkeitsparcours aus Holz und Seilen bieten genügend Spielfläche für die Kids um sich auszutoben, zu rutschen, zu klettern und neue Bewegungsformen auszutesten. Packt das Badezeug ein. An schönen Tagen könnt ihr euch im Badesee erfrischen.', 'Rufalipark, Obersaxen', 'Schweiz', 'Graubünden', NULL, '', false, 0, 'all_year', 'https://rufalipark.ch/', 46.7510929, 9.1205880, '2025-09-15 13:22:10', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(55, 1, 'Energiespielplatz Entlebuch', 'Mit Spiel und Spass nachhaltige Energien entdecken. Je mehr Kinder hier sind, desto spannender wird es auf dem Energiespielplatz Entlebuch, denn viele der Spielgeräte sind miteinander verknüpft. Ein Riesenspass, nicht nur für Nachwuchs-Ingenieure. Ganz nebenbei lernen die Kinder aber auch nachhaltige Energien kennen und erzeugen diese selber. Auch die Kleinsten kommen auf ihre Rechnung beim Planschen mit dem Wasser oder auf der Schaukel.', 'Energiespielplatz, Entlebuch', 'Schweiz', 'Luzern', NULL, '', false, 0, 'all_year', 'https://www.biosphaere.ch/de/poi/energiespielplatz-entlebuch', 46.9878541, 8.0592686, '2025-09-15 13:32:57', 'Wasserspiel', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(56, 1, 'Abenteuerspielplatz Fröschenmatt', 'Holz schleppen, sägen, hämmern, bauen, malen, basteln und vieles mehr. Hier darfst du eigene Hütten bauen und es gibt einiges mehr zu entdecken. Der Abenteuerspielplatz Fröschenmatt begrüsst seit 50 Jahren grosse und kleine Besucher auf dem 5''800m2 grossen Areal am Steinhauser Fussweg. Der Spielplatz bietet den Kindern genügend Platz zum Spielen, Klettern und auch, um ihre Kreativität auszuleben.', 'Abenteuerspielplatz Fröschenmatt, Zug', 'Schweiz', 'Zug', NULL, '', false, 0, 'spring,summer,autumn', 'https://www.froeschi.ch', 47.1813381, 8.4951151, '2025-09-16 12:52:18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(57, 1, 'Augusta Raurica', 'Augusta Raurica birgt eine Vielzahl historischer Schätze, darunter ein mysteriöser Brunnen, der als der größte Silberschatz aus der Spätantike gilt, sowie einen begehbaren Abwasserkanal römischen Ursprungs. Diese faszinierende Stätte ist buchstäblich eine Fundgrube für Geschichte und bietet unendliche Geheimnisse zum Entdecken.', 'Giebenacherstrasse 17, 4302 Augst', 'Schweiz', 'Basel-Landschaft', NULL, 'genügend vorhanden', false, 1, 'all_year', 'https://www.augustaraurica.ch/', 47.5340444, 7.7215489, '2025-09-16 12:55:21', 'Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(58, 1, 'Tierpark Goldau', 'Der Natur- und Tierpark Goldau liegt eingebettet in einer einzigartigen Landschaft, geprägt von imposanten Felsbrocken und idyllischen Wäldern. Der Park bietet Lebensraum für über 100 Wildtierarten, darunter Bären, Wölfe und Luchse, sowie zahlreiche weitere einheimische Tierarten. Mit einem Fokus auf Natur- und Artenschutz, Bildung und Forschung verfolgt der Natur- und Tierpark Goldau wichtige ideelle Ziele.', 'Tierpark, Goldau', 'Schweiz', 'Schwyz', NULL, 'genügend vorhanden', false, 3, 'all_year', 'https://www.tierpark.ch/', 47.0514811, 8.5539168, '2025-09-16 13:00:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(59, 1, 'Connyland', 'CONNY-LAND, da wirst du was erleben! Baden mit Seelöwen, kreischen auf der Cobra und auf Entdeckungstour im Jungle. Lust auf Spass und Abenteuer? Freue dich auf fröhliche Abenteuer und unvergessliche Momente mit der ganzen Familie! Unsere vielen Attraktionen garantieren für einen vergnüglichen, kurzweiligen und unbeschwerten Tag!', 'Connyland, Wäldi', 'Schweiz', 'Thurgau', NULL, 'genügend vorhanden', false, 3, 'spring,summer,autumn', 'https://www.connyland.ch/', 47.6143550, 9.0574462, '2025-09-16 13:04:48', 'mittlerer Park', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(60, 1, 'Erlebnisweg Teufenthal', 'Die Sage vom Schloss Liebegg und der Trostburg ist unterwegs in 7 Teilen zu lesen. Die Tafeln mit der Sage befinden sich jeweils bei den Ruhebänkli. Ebenso stehen für die kleinen Abenteurer 7 Kugelbahnen zur Verfügung, welche vom Teufenthaler Gewerbe erstellt wurden. Die Kugeln können am Kugelautomaten beim Gemeindehaus für 2 Franken bezogen werden.', 'Erlebnisweg, Teufenthal', 'Schweiz', 'Aargau', NULL, 'genügend vorhanden', true, 1, 'all_year', 'https://www.teufenthal.ch/freizeit/erlebnisweg-teufenthal.html/471', 47.3276148, 8.1186489, '2025-09-29 12:40:05', 'Kinderwagentauglich,Grillstelle,Chugelibahn', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(62, 1, 'Laguna Badeland', 'Den größten Genuss erlebt der Schwimmer, wenn er in der wohltemperierten Brandung des über 40 m langen Wellenbecken schwimmt und durch die große Glaspyramide in den Himmel oder in den Abendstunden zu den Sternen schauen kann.', 'Laguna Badeland, Weil am Rhein', 'Deutschland', 'Deutschland', NULL, 'genügend vorhanden', false, 2, 'all_year', 'https://laguna-badeland.de', 47.5862114, 7.6157682, '2025-10-01 15:50:31', 'kleine Badewelt,mit Aussenbereich,mit Innenbereich', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(66, 1, 'Kambly Erlebniswelt', 'Entdecken Sie in der Erlebniswelt von Kambly den Ursprung der Traditionsmarke und begeben Sie sich mit Kambly auf Entdeckungstour durch das Emmental.', 'Kambly, Trubschachen', 'Schweiz', 'Bern', NULL, 'genügend vorhanden', true, 0, 'all_year', 'https://kambly.com/de/kambly-erlebnis/erlebniswelt/', 46.9203513, 7.8496591, '2025-10-05 12:36:25', 'Innenspielplatz,Restaurant', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(69, 1, 'KidsVille', 'Der Kletterdschungel bietet den Kindern unzählige Wege, Tunnel und Klettermöglichkeiten. Es gibt wahnsinnig viel zu entdecken beim Abenteuer durch das Dschungel-Labyrinth. Die Highlights: Kletterdschungel mit vielen Abenteuerwegen und Hindernissen, grosses Trampolin, Moderne Softball-Shooter, Diverse Rutschbahnen, Vulkan-Kletterwand, Baumhäuser mit toller Aussicht, Rutschbahnen direkt ins bunte Bällebad.', 'KidsVille, Aarau', 'Schweiz', 'Aargau', NULL, '', false, 1, 'all_year', 'https://www.bowlingcenteraarau.ch/angebote-und-preise/kids-ville/', 47.3949818, 8.0644745, '2025-10-07 20:00:42', 'mittlerer Spielplatz', NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL),
(78, 1, 'Lasertag', 'Lasertag ist ein Actionspiel, das Teamfähigkeit und Geschick gegen die Gegner erfordert. Im riesigen, mehrstöckigen Areal befinden sich Rampen, Balkone, geniale Deckungen, Hindernisse und ein Flugzeug. Spielen Sie auf der mit Abstand grössten, modernsten und spektakulärsten Lasergame Anlage der Schweiz.', 'Actionworld, Obfelden', 'Schweiz', '', NULL, '', false, 4, 'all_year', 'https://www.actionworld.ch/lasertag', 47.2663571, 8.4228132, '2025-11-03 15:39:24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  beschreibung = EXCLUDED.beschreibung,
  adresse = EXCLUDED.adresse,
  land = EXCLUDED.land,
  region = EXCLUDED.region,
  parkplatz = EXCLUDED.parkplatz,
  parkplatz_kostenlos = EXCLUDED.parkplatz_kostenlos,
  kosten_stufe = EXCLUDED.kosten_stufe,
  jahreszeiten = EXCLUDED.jahreszeiten,
  website_url = EXCLUDED.website_url,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  nice_to_know = EXCLUDED.nice_to_know,
  dauer_min = EXCLUDED.dauer_min,
  dauer_max = EXCLUDED.dauer_max,
  distanz_min = EXCLUDED.distanz_min,
  distanz_max = EXCLUDED.distanz_max,
  is_rundtour = EXCLUDED.is_rundtour,
  is_von_a_nach_b = EXCLUDED.is_von_a_nach_b,
  altersempfehlung = EXCLUDED.altersempfehlung;

-- Update the sequence to match the highest ID
SELECT setval('ausfluege_id_seq', (SELECT MAX(id) FROM ausfluege));
